#!/bin/sh
rm /tmp/blitterRects* >/dev/null 2>/dev/null ;
fn=`date | sed 's, ,_,g'` ;
fn="/tmp/blitterRects_${fn}" ;
if (objects/unix/macasm $2 ${fn} && $1 ${fn} $3 ) then \
   st=0; else st=1; \
fi
rm ${fn}
exit ${st}
