               .title      Iserver error messages for VAX/VMS
               .facility   Iserver,1 /prefix=iserv_
               
               .severity   success
               
success        <Successfully terminated>

               .severity   informational
               
break          <Interrupted by user>
errorflag      <Error flag set by transputer>
misc           <Iserver terminated>

               .severity   warning
               
other          <Program terminated with user status>
fail           <Program terminated with failure>

               .end
