/*------------------------------------------------------------------------
--                                                                      --
--			H E L I O S   S E R V E R S			--
--			---------------------------			--
--                                                                      --
--             Copyright (C) 1991, Perihelion Software Ltd.             --
--                        All Rights Reserved.                          --
--                                                                      --
-- include.h								--
--                                                                      --
--	Header file for the include disk.				--
--                                                                      --
--	Author:  BLV 21.3.91						--
--                                                                      --
------------------------------------------------------------------------*/

/* $Header: /hsrc/servers/include/RCS/include.h,v 1.2 1991/11/08 20:17:29 bart Exp $ */

/**
*** This string defines the name of the include disk to be generated by
*** buildinc and read in by include
**/
#define IncludeDisk	"/helios/lib/incdisk"

typedef struct FileEntry {
	ObjNode	ObjNode;
	BYTE	Data[1];
} FileEntry;

