.TH MAX 3L
.SH NAME
max/min \- find the max/min of two ints
.SH SYNOPSIS
.nf
int max(a,b) 
int a,b;

int min(a,b) 
int a,b;
.fi
.SH DESCRIPTION
.I
max (min)
returns the integer max (min) of its arguments.
.SH AUTHOR
Robert E. Novak
.SH BUGS
None known
...
...	$Header: min.3,v 1.2 87/08/21 16:44:48 rnovak Exp $
...------------------------------------------------------------------
...
... $Source: /u3/syseng/rnovak/src/lib/RCS/min.3,v $
... $Revision: 1.2 $
... $Date: 87/08/21 16:44:48 $
... $State: Exp $
... $Author: rnovak $
... $Locker:  $
...
...------------------------------------------------------------------
... $Log:	min.3,v $
... Revision 1.2  87/08/21  16:44:48  rnovak
... moved the header to the bottom
... 
... Revision 1.1  87/08/21  16:33:45  rnovak
... Initial revision
... 
...------------------------------------------------------------------
...
