.TH MSTRCPY 3L
.SH NAME
mstrcpy \- copies a string into a newly malloc'ed array
.SH SYNOPSIS
.nf
char *
mstrcpy(str)
char * str ;
.fi
.SH DESCRIPTION
.I
mstrcpy
finds the length of its argument, mallocs an array one character
larger, copies the argument into the array and returns a pointer to
the malloc'ed array.
.SH AUTHOR
Robert E. Novak
.SH BUGS
None Known
...
...	$Header: mstrcpy.3,v 1.2 87/08/21 16:45:13 rnovak Exp $
...------------------------------------------------------------------
...
... $Source: /u3/syseng/rnovak/src/lib/RCS/mstrcpy.3,v $
... $Revision: 1.2 $
... $Date: 87/08/21 16:45:13 $
... $State: Exp $
... $Author: rnovak $
... $Locker:  $
...
...------------------------------------------------------------------
... $Log:	mstrcpy.3,v $
... Revision 1.2  87/08/21  16:45:13  rnovak
... moved the header to the bottom.
... 
... Revision 1.1  87/08/21  16:33:53  rnovak
... Initial revision
... 
...------------------------------------------------------------------
...
