.TH STRCAR 3L
.SH NAME
strcar/strcdr \- return a pointer to the car (cdr) of a string
.SH SYNOPSIS
.nf
char *
strcar(list,delimit)
char *	list ;
char *	delimit ;

char *
strcdr(list,delimit)
char *	list ;
char *	delimit ;
.fi
.SH DESCRIPTION
.I
strcar (strcdr)
returns a pointer to malloc'ed string which represents the car (cdr)
of list whose elements are separated by any characters in the delimit
list of characters.
.SH AUTHOR
Robert E. Novak
.SH BUGS
None known
...
...	$Header: strcdr.3,v 1.2 87/08/21 16:45:57 rnovak Exp $
...------------------------------------------------------------------
...
... $Source: /u3/syseng/rnovak/src/lib/RCS/strcdr.3,v $
... $Revision: 1.2 $
... $Date: 87/08/21 16:45:57 $
... $State: Exp $
... $Author: rnovak $
... $Locker:  $
...
...------------------------------------------------------------------
... $Log:	strcdr.3,v $
... Revision 1.2  87/08/21  16:45:57  rnovak
... moved the header to the bottom.
... 
... Revision 1.1  87/08/21  16:34:15  rnovak
... Initial revision
... 
...------------------------------------------------------------------
...
