.TH TRAVERSE 3WI "December 16, 1984"
.SH NAME
traverse \- recursively traverse a directory
.SH SYNOPSIS
.nf
traverse (path, func)
char	*path;
int 	(*func) ();

func (path, filetype, position)
char	*path;
.fi
.SH DESCRIPTION
traverse
applies its argument function func to its argument file pathname path.
If path is a directory,
then traverse applies func to all its entries.
This traversal is in depth first order
so that files are processed in the order
that they are stored in the directory.
.PP
The argument func should take three parameters:
a file name,
a file type,
and a position.
The call looks like this for directories:
.ce
(*func) (path, 'd', position);
and like this for other files:
.ce
(*func) (path, 'f', position);
The position
is 0 when path is first encountered
and 1 when traverse is done.
This is used to allow processing before and after
a directory is processed.
.SH EXAMPLE
.nf
list (name, type, pos)
char	*name;
	{
	if (type == 'd')
		printf ("%s %s\en", pos ? "Leaving" : "Entering", name);
	else /* type == 'f' */
		printf ("	%s\en", name);
	}
.fi
.SH AUTHOR
Gary Perlman
.SH BUGS
There are no diagnostics when directories cannot be searched.
...
...	$Header: traverse.3,v 1.2 87/08/21 16:46:21 rnovak Exp $
...------------------------------------------------------------------
...
... $Source: /u3/syseng/rnovak/src/lib/RCS/traverse.3,v $
... $Revision: 1.2 $
... $Date: 87/08/21 16:46:21 $
... $State: Exp $
... $Author: rnovak $
... $Locker:  $
...
...------------------------------------------------------------------
... $Log:	traverse.3,v $
... Revision 1.2  87/08/21  16:46:21  rnovak
... moved the header to the bottom.
... 
... Revision 1.1  87/08/21  16:34:23  rnovak
... Initial revision
... 
...------------------------------------------------------------------
...
