	PROGRAM WORKER

	INTEGER WORKERS, INTERVALS, POSITION, TEMP
	DOUBLE	PRECISION TOTAL, SUM
	INTEGER	FIRST, CURRENT, LAST
	DOUBLE	PRECISION WIDTH, TMP

	CALL POS_READ(  0, POSITION, 4)
	TEMP = POSITION + 1
	CALL POS_WRITE( 1, TEMP, 4)

	CALL POS_READ(  0, WORKERS, 4)
	CALL POS_WRITE( 1, WORKERS, 4)

	CALL POS_READ(  0, INTERVALS, 4)
	CALL POS_WRITE( 1, INTERVALS, 4)

	SUM = 0.0
	WIDTH = 1.0D0 / (WORKERS * INTERVALS)
	FIRST = POSITION * INTERVALS
	LAST  = FIRST + INTERVALS

	DO 100 CURRENT = FIRST,LAST-1,1
	TMP   = (CURRENT + 0.5D0) * WIDTH
	SUM   = SUM + WIDTH * (4.0D0 / (1.0D0 + TMP * TMP))
100	CONTINUE

	CALL POS_READ(  0, TOTAL, 8)
	TOTAL = TOTAL + SUM
	CALL POS_WRITE( 1, TOTAL, 8)

	END
