#
# makefile for various commands
#

.SUFFIXES:
.SUFFIXES: .z .o .s .c

INCDIR = /hsrc/include
LIBDIR = /hprod/C40/lib

sed:	sedexec.o sedcomp.o
	ldc40 $(LIBDIR)/cstart.o sedexec.o sedcomp.o -osed

.c.o:
	c -I$(INCDIR) $*.c -c



