.TH unyabba 1
.SH NAME
unyabba \- decompress data compressed with Y coding

unwhap \- decompress data compressed with AP coding
.SH SYNTAX
unyabba
[
\fB\-m\fImem
] [
\fB\-qQvrR\fI
] [
\fB\-ACHUVW\fI
]

\fBunwhap
[
\fB\-m\fImem
] [
\fB\-qQvrR\fI
] [
\fB\-ACHUVW\fI
]
.SH DESCRIPTION
.I unyabba
decompresses its standard input,
which must have come from
.I yabba,
and writes the result to its standard output.

.I unwhap
is like
.I unyabba,
but works with files from
.I whap.
Warning: If you use
.I unwhap
except for experimental use,
you may be infringing upon a patent.

Options
.B ACHUVW
print the authorship notice,
copyright notice,
help notice,
short usage summary,
version number,
and warranty information respectively.

.I unyabba
has several flags:
.TP 12
.B\-m\fImem
Assume that the input was produced for memory size
.I mem.
.I yabba
must have been given the same value of
.I mem.
.I mem
cannot be larger than a value specified at compile-time.
Typical values of
.I mem
are 12000, 20000, 40000, 65533, 200000, 500000, and 1000000.
.TP
.B\-r
Assume that the input was ``randomized''
by
.I yabba.
.I unyabba
will not expect its usual header,
and will strip out the pseudo-random information
introduced by
.I yabba.
Caveat:
.I unyabba
normally checks for the proper
.B\-m
setting in the input.
Under
.B\-r,
it cannot do so.
.TP
.B\-R
Look for the usual header, and complain about apparently random input.
This is the default.
.TP
.B\-v
.I unyabba
will be ``verbose'' and report compression statistics
to standard error.
.TP
.B\-q
Quiet.
.I unyabba
will not use
standard error in any way.
.TP
.B\-Q
Normal level of verbosity.
.PP
.B\-m,
.B\-r,
and
.B\-R
assume a different structure for the compressed file.
Be careful to have selected the same flags for
.I yabba.
.SH DIAGNOSTICS
.TP
\fIIn:\fB xxx \fIchars  Out:\fB xxx \fIchars  UnY'd from:\fB xx%
The utilizer of the computational machinery
has specified the ``verbose'' option
to
.I unyabba
via the
establishment of the character v
within an argument
preceded by a hyphen.
.TP
\fIfatal: output error\fB
Self-explanatory.
.TP
\fIfatal: input not in right format\fB
The
.I yabba
header is not there.
.TP
\fIfatal: input has \-m xxx, I have \-m yyy\fB
Self-explanatory.
.TP
\fIfatal: input corrupt
The input is not a compressed file. (Note that
.I unyabba
will always detect this, unlike
.I uncompress,
which may simply produce incorrect output.)
Did you compress with
.B\-r?
.SH "EXIT CODE"
0 normally, 1 for syntax errors or usage messages,
2 for output errors,
3 if the input is not in the right format,
4 if the input was compressed with a different value of
.I mem,
5 if the input is corrupt.
.SH FILES
None.
.SH BUGS
None known.
.SH VERSION
unwhap 1.00, March 19, 1991.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.SH REFERENCES
D. J. Bernstein, ``Y coding.''
Preprints available soon.
.SH "SEE ALSO"
yabba(1),
compress(1)
