.TH yabba 1
.SH NAME
yabba \- compress data with Y coding

whap \- compress data with AP coding
.SH SYNTAX
yabba
[
\fB\-m\fImem
] [
\fB\-z\fInum
] [
\fB\-Z\fIfuzz
] [
\fB\-qQv^rR\fI
] [
\fB\-ACHUVW\fI
]

\fBwhap
[
\fB\-m\fImem
] [
\fB\-z\fInum
] [
\fB\-Z\fIfuzz
] [
\fB\-qQv^rR\fI
] [
\fB\-ACHUVW\fI
]
.SH DESCRIPTION
.I yabba
compresses its standard input
and writes the result to its standard output.
\fIyabba\fBd
files can be restored
with
\fIunyabba\fB.

.I whap
is like
.I yabba,
but uses AP coding.
Warning: If you use
.I whap
except for experimental use,
you may be infringing upon a patent.

Options
.B ACHUVW
print the authorship notice,
copyright notice,
help notice,
short usage summary,
version number,
and warranty information respectively.

.I yabba
has several flags:
.TP 12
.B\-m\fImem
Produce output for memory size
.I mem.
.I unyabba
must be given the same value of
.I mem.
.I mem
cannot be larger than a value specified at compile-time;
if you compress with a
.I mem
larger than the maximum value for the
target
.I unyabba,
you will not be able to decompress the file.
Typical values of
.I mem
are 12000, 20000, 40000, 65533, 200000, 500000, and 1000000.
.TP
.B\-r
Produce ``randomized'' output suitable for encryption.
.I yabba
will introduce
pseudo-random bits of information
into the output, and will leave off its usual output header.
Normally, for efficiency and so that
.I yabba
can produce output before seeing the end of the input,
compressed texts must have some slight output redundancy.
Under
.B\-r,
most of this redundancy disappears
and almost all
\fIY'\fBd
texts are possible.
Caveat: the beginning
of the output depends only
on the beginning
of the input,
so you should make sure
to
.I precede the uncompressed input
.I by unpredictable data
before feeding it to
.I yabba.
.TP
.B\-R
Do not randomize output, and include the usual header.
This is the default.
.TP
.B\-Z\fIfuzz
.I yabba
maintains a
``dictionary''
of strings
adapted to the data seen so far.
When
.I yabba
runs out of memory (as specified by
.B\-m),
it will periodically test whether the compression ratio is
good enough.
If not, it will adapt to the next ``block''
of the file
by throwing out the dictionary and starting over.
.I fuzz
has some vaguely defined effect
on what ``good enough'' means;
the higher
.I fuzz
is, the longer
.I yabba
will hold out before clearing the dictionary.
.I fuzz
is 30 by default.
.TP
.B\-z\fInum
.I num
sets how often
.I yabba
will check for clearing the dictionary.
The default is every 8192 characters.
.TP
.B\-v
.I yabba
will be ``verbose'' and report compression statistics
to standard error.
.TP
.B\-^
Same as
.B\-v,
but reports the percent saved rather than the percent left.
.TP
.B\-q
Quiet.
.I yabba
will not use
standard error in any way.
.TP
.B\-Q
Normal level of verbosity.
.PP
.B\-m,
.B\-r,
and
.B\-R
change the structure of the compressed file.
Be careful to select the same flags for
.I unyabba.
.SH DIAGNOSTICS
.TP
\fIIn:\fB xxx \fIchars  Out:\fB xxx \fIchars  Y'd to:\fB xx%
The utilizer of the computational machinery
has specified the ``verbose'' option
to
.I yabba
via the
establishment of the character v
within an argument
preceded by a hyphen.
.TP
\fIfatal: output error\fB
Self-explanatory.
.SH "EXIT CODE"
0 normally, 1 for syntax errors or usage notices,
2 for output errors.
.SH FILES
None.
.SH BUGS
None known.
.SH VERSION
yabba 1.00, March 19, 1991.
.SH AUTHOR
Placed into the public domain by Daniel J. Bernstein.
.SH REFERENCES
D. J. Bernstein, ``Y coding.''
Preprints available soon.
.SH "SEE ALSO"
unyabba(1),
compress(1)
