#------------------------------------------------------------------------------
# Makefile for ARM Helios Serial device driver and server

LIB      = /helios/lib
BIN      = /helios/bin/private
DEFS     = ${LIB}/cstart.o ${LIB}/servlib.def ${LIB}/abclib.def
LIBS     = ${LIB}/kernel.def ${LIB}/syslib.def ${LIB}/util.def \
		${LIB}/abclib.def
LINK     = armlink
CC       = ncc
COMMON   = ../common
INCLUDE  = /hsrc/include
HINCLUDE = ${INCLUDE}/hobjasm
INCLUDES = -j. -j${INCLUDE}
HOBJASM  = hobjasm

#------------------------------------------------------------------------------

all:	serial serialdev.dev serialtest

install: smessage serialdev.dev serial serialtest
	cp serialdev.dev ${LIB}
	cp serial ${LIB}
	cp serialtest ${BIN}

clean:
	rm serialdev.dev
	rm serial
	rm serialtest

#------------------------------------------------------------------------------

smessage:
	@echo "                                   [[[ Making the serial device driver]]]"

#------------------------------------------------------------------------------

${COMMON}/modend.o:	${COMMON}/modend.s
			make -C ../common modend.o

#------------------------------------------------------------------------------

serialdev.dev: serialprefix.o serialdev.o ${COMMON}/modend.o
	${LINK} $^ ${LIBS} -o$@

serialdev.o: serialdev.c serialdev.h ${INCLUDE}/dev/result.h 
	${CC} ${INCLUDES} -Zps1 -Zr -c serialdev.c

serialprefix.o: serialprefix.s
	${HOBJASM} $*.s $@ -hdr ${HINCLUDE} -smt

#------------------------------------------------------------------------------

serial: serial.c serialdev.h ${INCLUDE}/dev/result.h
	${CC} -Zt -c ${INCLUDES} serial.c
	${LINK} -o$@ -nserial -s10000 ${DEFS} serial.o

#------------------------------------------------------------------------------
 
serialtest: serialtest.c serialdev.h ${INCLUDE}/dev/result.h
	${CC} -Zt -c ${INCLUDES} serialtest.c
	${LINK} -o$@ -s10000 ${LIB}/cstart.o ${LIB}/fault.def serialtest.o

#------------------------------------------------------------------------------
