default:
	@ cd .. ; unset MAKEFLAGS ; make ccc40

all:
	@ cd .. ; unset MAKEFLAGS ; make all

clean:
	@ cd .. ; unset MAKEFLAGS ; make clean-HP

install:
	@ cd .. ; unset MAKEFLAGS ; make install-HP

