.TH OGRE 6
.UC 4
.SH NAME
Ogre - a game of tank warfare in the 21st century.
.SH SYNOPSIS
/usr/games/ogre [ogre type (3 or 5)]
.SH DESCRIPTION
.PP
Ogre is a game of tank warfare in the 21st century.  You command a force of
infantry, armor, and howitzers pitted against a giant cybernetic tank, the
Ogre.  Your mission is to destroy the Ogre, or at least render it immobile,
before it reaches and destroys your command post.
.PP
A more complete reference on how to play can be found in the Ogre rule book
for the Metagaming MicroGame, now distributed by Steve Jackson's company.
Here's some very sketchy and incomplete documentation for Ogre players:
.PP
The game has the following phases:
.PP
1) Initialization.  The player's armor units, infantry, and command post
are placed on the map.  Nothing can be placed on the leftmost 7
columns of hexes, or on craters (*'s), or on any unit already placed.
Valid commands are:
.nf

           w   e

        a         d    (hex movement keys)

           z   x

            place a:

        H   howitzer
        T   heavy tank
        M   missile tank
        G   GEV
        1   1 infantry unit
        2   2 infantry units
        3   3 infantry units
        I   3 infantry units
        C   command post
        U   undo - pick up the unit
.fi

on the space currently pointed at by the cursor.
.PP
Units are displayed as these characters, except infantry, which appear
as '1', '2', or '3' depending on the number of units in the hex.
.PP
After placing the command post, you will be asked what its movement
allowance should be. You may give the CP a movement allowance of
0, 1, or 2 hexes. Each point of movement allowance you give the CP
will cost one armor point. Note that you must have enough armor
points left to provide the CP the desired movement. In any case, a
movement of 0 is always valid.
.PP
2) The Ogre (an O) now appears.
.PP
3) You are given the opportunity to move all your vehicles and infantry
that can move.  The cursor motion keys are used to move the unit indicated
by the cursor.  Additionally, the following commands are available:
.TP
.B 's',' '
Stop moving the unit where it is.
.TP
.B 'p'
Put this unit back where it started, and move it later.
.PP
No vehicle can move through a crater hex, or end it's movement on a friendly
unit, with the exception of infantry (see below).
Moving through the hex occupied by the Ogre is an attempt to ram the
Ogre.  This reduces the Ogre's treads by some amount, and destroys the
unit.
.PP
4) You now fire all your vehicles in range at designated targets on the
Ogre.  The following commands are used:
.TP     
.B m  
fire at missiles
.TP
.B b   
fire at main batteries
.TP
.B s   
fire at secondary batteries
.TP        
.B a   
fire at anti-personnel guns
.TP        
.B t   
fire at treads
.PP
The odds of destroying the target are displayed, but no action
is taken until 'r' is used, or until you run out of attack points.
(except for attacks on treads - see below.)
(in the odds display, '+' means a sure thing.)
.TP 
.B p   
Pass. The unit is passed over, and given the opportunity to fire
later.
.TP        
.B r   
Resolve all allocations so far, and display the results.  This
is implied by 't', as tread attacks cannot be grouped.  A resolve
is done automatically when you run out of attacking units.
.PP
5) Second movement phase for GEVs.  Just like step 3, except that only GEVs
can move.
.PP
6) The Ogre moves.  If it runs over any of your units, they are damaged
or destroyed.
.PP
7) The Ogre fires at all units in range.  Destroyed units are removed from
the map.  Disabled units are displayed in lower case, and may not
move or fire until the end of the NEXT Ogre attack.
.PP
Steps 3 through 7 are repeated until either
a) the Ogre has no movement points left, in which case you win, or
b) your command post is destroyed, in which case the Ogre wins.
.SH MISCELLANEOUS
.PP
In general, you cannot have more than one unit in a hex (no stacking),
except for infantry. You may have as many as three infantry units in a hex.
Instead of an 'I' to indicate infantry, the number of units in the hex is
displayed.  Even when stacked, infantry units still attack, defend, and
move as seperate units.  Currently, the only place where this game differs
from the board game is that the ogre may use AP on a hex with multiple
units in it once per unit, as opposed to once per hex.
.PP
The display "a/r Dd Mm" means the unit concerned attacks at a, at range r,
defends at d, and moves m hexes per turn.
.PP
The Ogre by default is a Mark III.  An argument of '5' on the command line
makes it a Mark V, and gives you more armor points.
.PP
The game can be interrupted at any point with a control-C.  There's now
no way to restart.
.PP
The screen can be redrawn (after say a control-Z) with a control-L.
.PP
The paper game is copyright (c) 1977 by Steve Jackson.  This computer
implementation is copyright (c) 1984 by Michael Caplinger.
Modifications copyright (c) 1984 by Mike Meyer.
.SH AUTHOR
Michael Caplinger, Rice University (mike@rice.ARPA), from a Microgame of the
same name published by Metagaming of Austin, Texas, and written by Steve
Jackson.  This implementation is not authorized in any way by Mr. Jackson,
and should not be sold for profit.
.SH SEE ALSO
termcap(5)
.SH BUGS
.PP
The Ogre sometimes gets confused and doesn't know where to go, so it
oscillates from one hex to another, and then back.
