.TH ROT 6 
.SH NAME
rot \- a visual demonstration of
.I software
.I rot.
.SH SYNOPSIS
.B rot
<file>
.PP
This program cascades letters from the top of the terminal screen
to the bottom in a waterfall effect.
.PP
This program reads from standard input and can be used as
an output
filter.
An amusing use is:
.sp
	man rot | col -b | rot
.SH AUTHOR
.PP
Original source from Peter da Silva
.br
	(ihnp4!shell!neuro1!hyd-ptd!peter) or
.br
	(ihnp4!shell!neuro1!datafact!peter) or
.br
	(ihnp4!shell!neuro1!baylor!peter).
.sp
Makefile and README from Bill Randle (billr@tekred.TEK.COM).
.sp
Man page from John G Dobnick
.br
	(ihnp4!uwmcsd1!jgd) or
.br
	(jgd@csd1.milw.wisc.edu).
.sp
Bug fixes from:
.br
	James Buster (bitbug@ucscb.ucsc.edu)
.br
 	Ed Falk (ed@sun -?)
.br
 	Andrew Klossner (andrew@lemming.gwd.tek.com)
.br
 	Andrew Scott Beals (bandy@amdcad.amd.com)
.br
	Colin Plumb (ccplumb@watmath.uucp)
.br
 	Bill Randle (billr@tekred.tek.com)
.SH BUGS
This is pretty slow at lower baudrates.
