default: all

all: ddetest mslights gditest

mslights: mslights.c
	c mslights.c -lwindows.lib -lRmLib -omslights

gditest: gditest.c
	c gditest.c -lwindows.lib -ogditest

ddetest: ddetest.c
	c ddetest.c -lwindows.lib -oddetest

