/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs_prot.h"

bool_t
xdr_nfsstat(xdrs, objp)
	register XDR *xdrs;
	nfsstat *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ftype(xdrs, objp)
	register XDR *xdrs;
	ftype *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfs_fh(xdrs, objp)
	register XDR *xdrs;
	nfs_fh *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_opaque(xdrs, objp->data, NFS_FHSIZE))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfstime(xdrs, objp)
	register XDR *xdrs;
	nfstime *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_int(xdrs, &objp->seconds))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->useconds))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fattr(xdrs, objp)
	register XDR *xdrs;
	fattr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif


	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_ftype(xdrs, &objp->type))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->mode))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->nlink))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->uid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->gid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->size))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocksize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->rdev))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocks))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->fsid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->fileid))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_INT32(buf, objp->mode);
			IXDR_PUT_U_INT32(buf, objp->nlink);
			IXDR_PUT_U_INT32(buf, objp->uid);
			IXDR_PUT_U_INT32(buf, objp->gid);
			IXDR_PUT_U_INT32(buf, objp->size);
			IXDR_PUT_U_INT32(buf, objp->blocksize);
			IXDR_PUT_U_INT32(buf, objp->rdev);
			IXDR_PUT_U_INT32(buf, objp->blocks);
			IXDR_PUT_U_INT32(buf, objp->fsid);
			IXDR_PUT_U_INT32(buf, objp->fileid);
#else
			IXDR_PUT_U_LONG(buf, objp->mode);
			IXDR_PUT_U_LONG(buf, objp->nlink);
			IXDR_PUT_U_LONG(buf, objp->uid);
			IXDR_PUT_U_LONG(buf, objp->gid);
			IXDR_PUT_U_LONG(buf, objp->size);
			IXDR_PUT_U_LONG(buf, objp->blocksize);
			IXDR_PUT_U_LONG(buf, objp->rdev);
			IXDR_PUT_U_LONG(buf, objp->blocks);
			IXDR_PUT_U_LONG(buf, objp->fsid);
			IXDR_PUT_U_LONG(buf, objp->fileid);
#endif
		}
		if (!xdr_nfstime(xdrs, &objp->atime))
			return (FALSE);
		if (!xdr_nfstime(xdrs, &objp->mtime))
			return (FALSE);
		if (!xdr_nfstime(xdrs, &objp->ctime))
			return (FALSE);
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_ftype(xdrs, &objp->type))
			return (FALSE);
		buf = XDR_INLINE(xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->mode))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->nlink))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->uid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->gid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->size))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocksize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->rdev))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocks))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->fsid))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->fileid))
				return (FALSE);

		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->mode = IXDR_GET_U_INT32(buf);
			objp->nlink = IXDR_GET_U_INT32(buf);
			objp->uid = IXDR_GET_U_INT32(buf);
			objp->gid = IXDR_GET_U_INT32(buf);
			objp->size = IXDR_GET_U_INT32(buf);
			objp->blocksize = IXDR_GET_U_INT32(buf);
			objp->rdev = IXDR_GET_U_INT32(buf);
			objp->blocks = IXDR_GET_U_INT32(buf);
			objp->fsid = IXDR_GET_U_INT32(buf);
			objp->fileid = IXDR_GET_U_INT32(buf);
#else
			objp->mode = IXDR_GET_U_LONG(buf);
			objp->nlink = IXDR_GET_U_LONG(buf);
			objp->uid = IXDR_GET_U_LONG(buf);
			objp->gid = IXDR_GET_U_LONG(buf);
			objp->size = IXDR_GET_U_LONG(buf);
			objp->blocksize = IXDR_GET_U_LONG(buf);
			objp->rdev = IXDR_GET_U_LONG(buf);
			objp->blocks = IXDR_GET_U_LONG(buf);
			objp->fsid = IXDR_GET_U_LONG(buf);
			objp->fileid = IXDR_GET_U_LONG(buf);
#endif
		}
		if (!xdr_nfstime(xdrs, &objp->atime))
			return (FALSE);
		if (!xdr_nfstime(xdrs, &objp->mtime))
			return (FALSE);
		if (!xdr_nfstime(xdrs, &objp->ctime))
			return (FALSE);
		return (TRUE);
	}

	if (!xdr_ftype(xdrs, &objp->type))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->nlink))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->blocksize))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->rdev))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->blocks))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->fsid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->fileid))
		return (FALSE);
	if (!xdr_nfstime(xdrs, &objp->atime))
		return (FALSE);
	if (!xdr_nfstime(xdrs, &objp->mtime))
		return (FALSE);
	if (!xdr_nfstime(xdrs, &objp->ctime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_sattr(xdrs, objp)
	register XDR *xdrs;
	sattr *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_int(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_nfstime(xdrs, &objp->atime))
		return (FALSE);
	if (!xdr_nfstime(xdrs, &objp->mtime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_filename(xdrs, objp)
	register XDR *xdrs;
	filename *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, objp, NFS_MAXNAMLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfspath(xdrs, objp)
	register XDR *xdrs;
	nfspath *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, objp, NFS_MAXPATHLEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_attrstat(xdrs, objp)
	register XDR *xdrs;
	attrstat *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_fattr(xdrs, &objp->attrstat_u.attributes))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_sattrargs(xdrs, objp)
	register XDR *xdrs;
	sattrargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_sattr(xdrs, &objp->attributes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_diropargs(xdrs, objp)
	register XDR *xdrs;
	diropargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->dir))
		return (FALSE);
	if (!xdr_filename(xdrs, &objp->name))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_diropokres(xdrs, objp)
	register XDR *xdrs;
	diropokres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_fattr(xdrs, &objp->attributes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_diropres(xdrs, objp)
	register XDR *xdrs;
	diropres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_diropokres(xdrs, &objp->diropres_u.diropres))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_readlinkres(xdrs, objp)
	register XDR *xdrs;
	readlinkres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_nfspath(xdrs, &objp->readlinkres_u.data))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_readargs(xdrs, objp)
	register XDR *xdrs;
	readargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->count))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->totalcount))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_readokres(xdrs, objp)
	register XDR *xdrs;
	readokres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_fattr(xdrs, &objp->attributes))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, NFS_MAXDATA))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_readres(xdrs, objp)
	register XDR *xdrs;
	readres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_readokres(xdrs, &objp->readres_u.reply))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_writeargs(xdrs, objp)
	register XDR *xdrs;
	writeargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->beginoffset))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->totalcount))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, NFS_MAXDATA))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_createargs(xdrs, objp)
	register XDR *xdrs;
	createargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_diropargs(xdrs, &objp->where))
		return (FALSE);
	if (!xdr_sattr(xdrs, &objp->attributes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_renameargs(xdrs, objp)
	register XDR *xdrs;
	renameargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_diropargs(xdrs, &objp->from))
		return (FALSE);
	if (!xdr_diropargs(xdrs, &objp->to))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_linkargs(xdrs, objp)
	register XDR *xdrs;
	linkargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->from))
		return (FALSE);
	if (!xdr_diropargs(xdrs, &objp->to))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_symlinkargs(xdrs, objp)
	register XDR *xdrs;
	symlinkargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_diropargs(xdrs, &objp->from))
		return (FALSE);
	if (!xdr_nfspath(xdrs, &objp->to))
		return (FALSE);
	if (!xdr_sattr(xdrs, &objp->attributes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfscookie(xdrs, objp)
	register XDR *xdrs;
	nfscookie objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_opaque(xdrs, objp, NFS_COOKIESIZE))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_readdirargs(xdrs, objp)
	register XDR *xdrs;
	readdirargs *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfs_fh(xdrs, &objp->dir))
		return (FALSE);
	if (!xdr_nfscookie(xdrs, objp->cookie))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->count))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_entry(xdrs, objp)
	register XDR *xdrs;
	entry *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_int(xdrs, &objp->fileid))
		return (FALSE);
	if (!xdr_filename(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_nfscookie(xdrs, objp->cookie))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->nextentry, sizeof (entry), (xdrproc_t) xdr_entry))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_dirlist(xdrs, objp)
	register XDR *xdrs;
	dirlist *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_pointer(xdrs, (char **)&objp->entries, sizeof (entry), (xdrproc_t) xdr_entry))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->eof))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_readdirres(xdrs, objp)
	register XDR *xdrs;
	readdirres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_dirlist(xdrs, &objp->readdirres_u.reply))
			return (FALSE);
		break;
	}
	return (TRUE);
}

bool_t
xdr_statfsokres(xdrs, objp)
	register XDR *xdrs;
	statfsokres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->tsize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bsize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocks))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bfree))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bavail))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			IXDR_PUT_U_INT32(buf, objp->tsize);
			IXDR_PUT_U_INT32(buf, objp->bsize);
			IXDR_PUT_U_INT32(buf, objp->blocks);
			IXDR_PUT_U_INT32(buf, objp->bfree);
			IXDR_PUT_U_INT32(buf, objp->bavail);
#else
			IXDR_PUT_U_LONG(buf, objp->tsize);
			IXDR_PUT_U_LONG(buf, objp->bsize);
			IXDR_PUT_U_LONG(buf, objp->blocks);
			IXDR_PUT_U_LONG(buf, objp->bfree);
			IXDR_PUT_U_LONG(buf, objp->bavail);
#endif
		}
		return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->tsize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bsize))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->blocks))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bfree))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->bavail))
				return (FALSE);
		} else {
#if defined(_LP64) || defined(_KERNEL)
			objp->tsize = IXDR_GET_U_INT32(buf);
			objp->bsize = IXDR_GET_U_INT32(buf);
			objp->blocks = IXDR_GET_U_INT32(buf);
			objp->bfree = IXDR_GET_U_INT32(buf);
			objp->bavail = IXDR_GET_U_INT32(buf);
#else
			objp->tsize = IXDR_GET_U_LONG(buf);
			objp->bsize = IXDR_GET_U_LONG(buf);
			objp->blocks = IXDR_GET_U_LONG(buf);
			objp->bfree = IXDR_GET_U_LONG(buf);
			objp->bavail = IXDR_GET_U_LONG(buf);
#endif
		}
		return (TRUE);
	}

	if (!xdr_u_int(xdrs, &objp->tsize))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->bsize))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->blocks))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->bfree))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->bavail))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_statfsres(xdrs, objp)
	register XDR *xdrs;
	statfsres *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nfsstat(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS_OK:
		if (!xdr_statfsokres(xdrs, &objp->statfsres_u.reply))
			return (FALSE);
		break;
	}
	return (TRUE);
}
