.TH COOKIE 6
.SH NAME
cookie \- show a fortune cookie
.SH SYNOPSIS
.B cookie
[ sayings hash-file ]
.sp
.B /usr/local/lib/cookhash
< sayings > hash-file
.SH DESCRIPTION
.I Cookie
shows the user a randomly chosen quote from a file containing
fortune cookies, sayings, jokes, aphorisms, quotes and so on.
Those likely to be offended by words and ideas that are
alien to them are asked to not read the cookie file.
If you find quotes in the file that are unattributed and you know the
attributions, please mail them to karl@sugar.uu.net or uunet!sugar!karl.
.P
Cookie can also be executed with two arguments, the name of a cookie file
followed by the name of its hash file.
To create the hash file, use
.I /usr/local/lib/cookhash
which reads the sayings from standard input and writes the hash values to
standard output.
Sayings within the input file are separated by lines containing 
.B %% .
.SH SEE ALSO
fortune(6)
.SH FILES
/usr/local/lib/sayings, /usr/local/lib/sayhash
.SH AUTHOR
Karl Lehenbauer @ The Hacker's Haven, Missouri City, Texas -- 12-Jan-89
