#! /bin/sh
#
#
# vc40load
#
drv_dir=driver
drv_name=vc40
drv_ofile=${drv_name}.o
envvar_name=V40DSP
envvar_val=${VC40DSP}
entry=_vc40_init

if [ a$1 != a ]
then
	drvdir=$1
elif [ a${envvar_val} != a ]
then
	drvdir=${envvar_val}/${drv_dir}
else
	echo No directory specified and ${envvar_name} is not set.
	echo ${drv_name} driver not loaded
	exit
fi
if [ a$2 != a ]
then
	drv_ofile=$2
fi

if [ ! -d ${drvdir} ]
then
	echo Directory ${drvdir} does not exist!
	echo ${drv_name} driver not loaded
	exit
fi
if [ ! -f ${drvdir}/${drv_ofile} -a ! -h ${drvdir}/${drv_ofile} ]
then
	echo Cannot find the driver file ${drv_ofile}
	echo ${drv_name} driver not loaded
	exit
fi

a=`/usr/etc/modstat|grep ${drv_name}`
if [ "a$a" != "a" ]
then
	echo unloading previously loaded ${drv_name} driver
	set $a
	sync; sync
	/usr/etc/modunload -id $1
	if [ $? -ne 0 ] ; then exit ; fi
fi

echo loading ${drv_name} driver
cd ${drvdir}
sync ; sync
/usr/etc/modload ${drvdir}/${drv_ofile} -entry ${entry} -exec ${drvdir}/${drv_name}PostLoad -conf ${drv_name}.conf
if [ -f /tmp/${drv_name} ]
then
	rm -f /tmp/${drv_name}
fi
sync ; sync

