# make file for "flex" tool

# the first time around use "make first_flex"

SKELETONFILE = \"/helios/local/lib/flex/skel.flx\"
FSKELETONFILE = \"/helios/local/lib/flex/fastskel.flx\"
CFLAGS = -wA -DPCNAMES -DSV -DDEFAULT_SKELETON_FILE=$(SKELETONFILE)\
         -DFAST_SKELETON_FILE=$(FSKELETONFILE)
LDFLAGS = -s10000
CC = c

OBJS = ccl.o dfa.o ecs.o main.o misc.o nfa.o \
         parse.o scan.o sym.o tblcmp.o yylex.o ../bison/alloca.o
LEX = flex -s -i

flex : $(OBJS)
	$(CC) $(LDFLAGS) -o flex $(OBJS)

../bison/alloca.o : ../bison/alloca.c
	cd ../bison; make alloca.o

scan.o : parse.h
#scan.c : scan.l
parse.h parse.c : parse.y
	bison -d -y parse.y
	mv y-tab.c parse.c
	mv y-tab.h parse.h

# first_flex:
#    cp scan.c.dist scan.c
#    make $(MFLAGS) flex
# 
# comment-out the next two lines after a successful "make test" and
# comment-in the following two lines.

# scan.c : scan.l
#    $(FLEX) $(FLEX_FLAGS) scan.l >scan.c
# 
# scan.o : scan.c parse.h
# 
# main.o : main.c
#    cc $(CFLAGS) -c $(SKELFLAGS) main.c
# 
# flex.lint : $(FLEX_C_SOURCES)
#    @echo "Expect a \"may be used before set\" and 2 \"unused\"'s
#    lint $(FLEX_C_SOURCES) > flex.lint

# clean :
#    rm -f core errs flex *.o parse.c *.lint parse.h
# 
# test :
#    $(FLEX) $(FLEX_FLAGS) scan.l | diff scan.c -
