/*******************************************************************************
**
**  This file was created via the 'gem'-command
**  using the file "fs.er".
**  Changes have to be done in the same way.
**
*******************************************************************************/

                                                                                /*
  []-------------------------------------------------------------------------[]
   |                                                                         |
   |                    (c) 1992 by parsytec GmbH, Aachen                    |
   |                          All rights reserved.                           |
   |                                                                         |
   |-------------------------------------------------------------------------|
   |                                                                         |
   |                             Error handling                              |
   |                                                                         |
   |-------------------------------------------------------------------------|
   |                                                                         |
   |  History:                                                               |
   |    Generated, see above.                                                |
   |                                                                         |
  []-------------------------------------------------------------------------[]
                                                                                */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define  DEBUG    0
#define  GEPDEBUG 0
#define  FLDEBUG  0

#include "error.h"
#include "fstring.h"
#include "fserr.h"

char *FSErr [] =
      {
        "",
        "Usage: remote <MSCboard> fs [-c][-f|-b|-n] [<DevInfoName>] <FileServer>",
        "Failed to load devinfo.",
        "Failed to find filesystem info.",
        "Failed to find discdevice info.",
        "Illegal partitioning.",
        "Failed to open device.",
        "Failed to init device info for fileserver.",
        "Illegal partition allocation.",
        "Not enough memory for PFS v2.1.",
        "Failed to allocate memory for server.",
        "-- PFS v2.1 started -- (Compiled: %s, %s)",
        "-- PFS v2.1 finished --",
        "PFS: %F %s",
        "Not enough memory for PFS v2.1.\n             free   : %d byte\n             needed : %d byte (absolute minimum)",
        "Not enough memory to fork tdispatch for volume %d and following.",
        "Volume /%s failed to get link data block.",
        "Volume /%s failed to write link data block.",
        "Volume /%s: do_closeobj () not yet implemented.",
        "Parsytec Filesystem  Rel. 920320  v2.1 (c) Copyright 1992 Parsytec GmbH",
        "Running...",
        "blknr == %d is in addr == %d",
        "Volume /%s failed to get block.",
        "Volume /%s failed to write block.",
        "Volume /%s failed to read s.i.block.",
        "Volume /%s failed to write s.i.block.",
        "Volume /%s failed to read d.i.block.",
        "Volume /%s failed to write i.block.",
        "Volume /%s failed to read summary block.",
        "Volume /%s failed to write summary block.",
        "Volume /%s failed to write i.block.",
        "Volume /%s failed to read info block.",
        "Volume /%s failed to write info block.",
        "Volume /%s failed to update info block.",
        "Volume /%s failed to update summary info.",
        "Volume /%s : ERROR : TIND data blocks not implemented.",
        "Volume /%s : ERROR : never should be here.",
        "Volume /%s reached number of minimum free blocks (%d).",
        "Volume /%s, file system is totally full.",
        "Volume /%s failed to free indirect block.",
        "Volume /%s failed to free double indirect block.",
        "Volume /%s failed to init size info.",
        "Volume /%s failed to write boot block.",
        "Volume /%s failed to write summary block.",
        "Volume /%s, invalid summary block found. Call the checker.",
        "Volume /%s failed to init summary info.",
        "Volume /%s failed to read summary block.",
        "Volume /%s failed to write info block of cyl.group %d.",
        "Volume /%s, info block 0 physically destroyed.",
        "Volume /%s failed to write root directory.",
        "Volume /%s failed to read directory block.",
        "Volume /%s failed to write directory block.",
        "Volume /%s failed to get message (0x%x).",
        "Volume /%s received unknown message (0x%x).",
        "Volume /%s failed to write block.",
        "Not allowed to write %d block(s) from blocknumber %d.",
        "Volume /%s, cgsize out of legal range (%d).",
        "Volume /%s, ncg out of legal range (%d).",
        "Volume /%s, cgoffset out of legal range (%d).",
        "Volume /%s failed to get valid superblock (info block 0).",
        "Could not read superblock of volume /%s.",
        "Volume /%s, failed to write superblock.",
        "Volume /%s, superblock on disc physically destroyed.",
        "Volume /%s, CHECKER failed.",
        "Could not get root inode of volume /%s.",
        "Write request skipped.",
        "Root inode of volume /%s not found.",
        "Unable to allocate %d bytes for %s.",
        "Reading device information from file \"%s\".",
        "Partition %d does not exist in device information file.",
        "Addressing size larger than file server blocksize.",
        "Addressing size does not fit into file server blocksize.",
        "Not enough space for any configuration (%d blocks).",
        "Not enough blocks per cylinder group (%d), it must be >= %d.",
        "Not enough space for volume %d. (Available: %d, requested: %d)",
        "Too few blocks (%d) for at least one cylinder group (%d blocks).",
        "Too few blocks (%d) to get enough blocks per cylinder group\n(minimum %d) for %d cylindergroups.",
        "Failed to allocate volume descriptor.",
        "Number of cylinder groups in volume %d too big (%d).",
        "Number of blocks per cylindergroup in volume %d too big (%d),\nit mist be <= %d.",
        "Failed to allocate partition descriptor for volume %d.",
        "Raw volume %d has more than one partition (%d).",
        "Partition %d is too small to work with the file server.",
        "Got a close request while writing to tape /%s.",
        "Rewinding tape /%s.",
        "Tape /%s closed.",
        "PFS: tape: %F %s %s",
        "fwCTXT : >%s<",
        "fwPATH : >%s<",
        "fwTRGT : >%s<",
        "PFS: tape: %F",
        "TAPE: read %d bytes from tape file %d",
        "TAPE: read %d bytes",
        "TAPE: read returning %d bytes, rc = %x,",
        "TAPE: write %d bytes to tape file %d",
        "TAPE: written %d bytes to tape file %d",
        "TAPE: req->Pos (= %d), req->Size = %d",
        "req->Pos != tape_position (= %d)",
        "TAPE: written %d bytes",
        "tape_seek: mode %d, newpos = %d",
        "tape_seek: newpos = %x",
        "Failed to allocate tape descriptor.",
        "Volume /%s has still (%d) active non-interuptable worker.",
        "Volume /%s has still (%d) active directory worker.\nUnable to unload or terminate right now.",
        "Volume /%s forced unload with (%d) active stream worker \n and (%d) active directory worker.",
        "Hardware error detected loading volume /%s.",
        "Device error detected loading volume /%s.",
        "init_volume_info () failed.",
        "Could not fork tworker.",
        "Unknown functioncode.",
        "PFS: tape: stream getmsg error 0x%x.",
        "Volume /%s function not implemented.",
        "Request size must be multiple of addressing size (%d).",
        "Position must be multiple of addressing size (%d).",
        "Failed to allocate tape buffer.",
        "-- CHECKER V1.2I on volume /%s started --",
        "%sTry to load volume again to restart checker.",
        "%sSTEP 1   : CHECKING BASIC DATA STRUCTURES",
        "%s***    Step 1.1 : Plausibility test of file-system parameters",
        "%s***    Step 1.2 : First inspection of bitmap-data",
        "%s***    Step 1.3 : Allocate memory for reference bit-map array",
        "%s***    Step 1.4 : Check the root directory inode",
        "%s***    Step 1.5 : Look for the '/lost+found'- directory",
        "%sSTEP 2   : TRAVERSING THE DIRECTORY TREE (INODE-CHECK)",
        "%sSTEP 3   : MAKE BLOCK-BASED CONNECTIVITY CHECKS",
        "%sSTEP 4   : TIDYUP EVERYTHING AND CORRECT SUMMARY INFORMATIONS",
        "-- CHECKER V1.2I on volume /%s finished --",
        "Try to interpret block no: %d as an info-block.",
        "Valid superblock in use now.",
        "Number of cylinder groups               Sb : %4d / devinfo : %d",
        "Size of a cylinder group                Sb : %4d / devinfo : %d",
        "Relative offset into a cylinder group   Sb : %4d / devinfo : %d",
        "Size of a of small packet               Sb : %d / devinfo : %d",
        "Size of a of medium packet              Sb : %d / devinfo : %d",
        "Size of a huge packet                   Sb : %d / devinfo : %d",
        "Number of samll packets                 Sb : %d / devinfo : %d",
        "Number of medium packtes                Sb : %d / devinfo : %d",
        "Number of huge packets                  Sb : %d / devinfo : %d",
        "Maximal number of incore inodes         Sb : %d / devinfo : %d",
        "Number of blocks to be kept free        Sb : %d / devinfo : %d",
        "%sThe bit-map is not usable.",
        "%sA new root-directory is created from scratch.",
        "%sA new '/lost+found' entry is created.",
        "%sHave created a new '/lost+found' directory.",
        "%sCHECKER INTERRUPTED DUE TO A FATAL ERROR CONDITION.",
        "%sFailed to allocate memory.",
        "%sCould not handle bad block after bread ().",
        "%sFailed to read an info block.",
        "%sFailed to read a summary block.",
        "%sFailed to bwrite () a block.",
        "%sFailed to handle directory block.",
        "%sFailed to handle link block.",
        "%sFailed to handle indirect block.",
        "%sFailed to handle double indirect block.",
        "%sError condition unknown.",
        "%sDURING BASIC DATA STRUCTURE CHECK",
        "%sFailed to read summary block (bnr 1).",
        "%sDURING SIMPLE OBJECT (INODE) CHECK",
        "%sDURING BIT-MAP AND CONNECTIVITY CHECK",
        "%sDURING TIDY UP OPERATION",
        "%sFailed to read info block 0 (bnr 2).",
        "The Superblock is damaged (%d errors counted).",
        "Unable to select a new info block automatically.",
        "%sFailed to read info block %d (bnr %d).",
        "%sInvalid cgnr (%d) found in info block %d.",
        "%sDifferent number of free blocks found.",
        "%s> Cyl. Group : %d   FREE  counted= %d   cg-summary= %d",
        "%sCorrupted bits in bit-map found.",
        "%s> Cyl. Group : %d   ERRORS       =%d  blocks",
        "%sUnable to allocate memory for reference bit-maps.",
        "%sThe root-directory is not usable.",
        "Unable to find a '/lost+found' entry in the root-directory.",
        "%sCannot create a new '/lost+found' directory.",
        "Read %d Bytes in %u centi-seconds.",
        "Wrote %d Bytes in %u centi-second.",
        "Volume /%s failed to read block.",
        "Volume /%s failed to write block.",
        "Volume /%s failed to get block.",
        "Volume /%s cannot read requested data.",
        "Volume /%s: PutMsg couldn't succeed (Error 0x%x).",
        "Volume /%s: GetMsg couldn't succeed (Error 0x%x).",
        "get_daddr:   bp = bread (%d, %d, 1, SAVEA);",
        "get_daddr:   bp = brelse (0x%p, TAIL);",
        "iget: >%s.%d<",
        "%s[%d]->|",
        "%d:%s |",
        "",
        "i_remove: %d",
        "Volume /%s failed to read indirect block.",
        "ERROR: TIND data blocks not implemented.",
        "No free inodes in freelist.",
        "Volume /%s failed to read directory block.",
        "Volume /%s failed to write directory block.",
        "ERROR: Can't read non allocated blocks.",
        "ERROR: Pathname is not absolute.",
        "ERROR: Illegal pathname (%s).",
        "ERROR: Incore i-list is full.",
        "%sBlock #%d has to be updated.",
        "%sFailed to write block %d.",
        "%s***    Step 4.1 : Handle all 'hanging' links found.",
        "%s                 ('hanging' links are deleted)",
        "%s                 ('hanging' links are not deleted)",
        "%sDeleting 'hanging' link which refers to : [%s]",
        "%sDetected 'hanging' link which refers to : [%s]",
        "%s***    Step 4.2 : Final comparison of ref-maps and bit-maps",
        "%s***    Step 4.3 : Update the summary informations for each cg",
        "%sHave to update summary block on disk.",
        "%sFailed to read directory block (bnr %d).",
        "%sFailed to read info block %d (bnr %d).",
        "%sFailed to read summary block.",
        "%sCgnr in info block %d is corrected to %d.",
        "%sFailed to read indirect block (bnr %d).",
        "%sFailed to read double indirect block (bnr %d).",
        "%sFailed to read block (bnr %d).",
        "Partition #%d overlaps partition #%d.",
        "You need at least one partition, of course.",
        "Illegal partition number (%d).",
        "Partition #%d is allocated twice.",
        "Volume /%s failed to swap packet.",
        "Volume /%s failed to get block.",
        "Buffer checksum error of volume /%s.\nBlock %d has an incorrect checksum.",
        "Illegal type in function procname (%s).",
        "Volume /%s failed to asynchron_write packet.",
        "Volume /%s must consist of one partition to format.",
        "FG_Open of vol %d, part %d returned GSP error code 0x%x.",
        "Volume %d must consist of one partition.",
        "Raw and structured devices must not be mixed in vol. %d.",
        "Loadable and nonloadable media mixed in vol. %d.",
        "Partition %d of volume %d has a different load status (%d instead of %d).",
        "Failed to unload vol %d, GSP error code 0x%x.",
        "Invalid parameter error of volume /%s.\nRequested to read %d block(s) starting from block %d.\nAvailable %d blocks per cylgroup, %d cylgroups.",
        "Invalid parameter error of volume /%s.\nRequested to write %d block(s) starting from block %d.\nAvailable %d blocks per cylgroup, %d cylgroups.",
        "Device error 0x%x during msc_read () of volume /%s.\nRequested %d block(s) starting from block %d,\nactually read %d block(s).",
        "Buffer cache checksum error of volume /%s.\nBlock %d has an incorrect checksum.",
        "Device error 0x%x during msc_write () of volume /%s.\nRequested %d block(s) starting from block %d,\nactually wrote %d block(s).",
        ""
      };

void FSErrPrint (void)
{
  FSErrKind E;

  for (E = FSOK; E < FSNOfErr; ++E)
    Report ("%s", FSErr [E]);
}
