.TH GNU CHESS
.SH NAME
gnuchess \- The Technology Chess Program for GNU Unix
.SH SYNOPSIS
.B gnuchess
.br
.B chesstool gnuchess
[
.I level
]
.SH DESCRIPTION
.I Gnuchess
plays a game of chess against the user. Or it plays against
itself. Or it referees a game.
.PP
.I Gnuchess
has two display modes. The first mode is simply a normal 
mode that you could use with a terminal. The second mode
is a fancy display mode you can use with a SUN workstation.
To use the former, simply type 'gnuchess'. To use the
latter, simply type 'chesstool gnuchess' on a SUN
workstation where 'chesstool' is installed. In the
latter example, the argument should be the path
specifying where to find the gnuchess binary.
.PP
The
.I level
option when using 'chesstool' allows setting the search level
time limit (in seconds).  The default is 30 seconds.  In other
display modes, the user is prompted for a time limit.  The
search limit can be changed with the "time" command.
.PP
The following documentation assumes you are in
the first mode (e.g. normal mode using a regular
terminal). If not, then you should read the chesstool documentation.
.PP
For help once in
.I Gnuchess
type "help". To type in your move, use the
notation "e2e4" where the first letter-number pair
indicates the origination square and the second
letter-number pair indicates the destination square.
The letter indicates the column with the left-most
column being "a" and the right-most column being "h".
The number indicates the row, the first row (White's
first rank) being "1" and the last row (Black's
first rank) being "8". To castle, type the origin
square of the king and the destination square of the
king, just as you would do for a regular move.
.SH LIST OF COMMANDS
.LP
.nf
Awindow		set Alpha window size
Bwindow		set Beta window size
bd		redraw board
beep		toggle beep
black		computer plays black
book		force computer to ignore opening book (?)
both		computer match
clock		set time control
contempt	?
debug		debug piece locations
depth		set search depth
easy		toggle easy mode
force		enter game moves
g1f3		move from g1 to f3
get		game from file
go		?
hash		toggle hashing
help		print help message
hint		suggest a move
list		game to chess.lst
new		start new game
nf3		move knight to f3
o-o		castle king side
o-o-o		castle queen side
post		principle variation
prune		prune search tree
quit		exit CHESS
random		randomize play
remove		undo last two moves
reverse		board display
save		game to file
set		edit board
switch		sides with computer
time		change search level
undo		undo last move
verify		verify move against the book (?)
white		computer plays white
.fi
.SH BUGS
.PP
There are probably some bugs. Suggestions for improvements
and bug reports should be mailed to the author.
.SH AUTHOR
.nf
Stuart Cracraft     Stuart Cracraft
P.O. Box 13123      UCLA, Dept. of Mathematics
Torrance, Ca.       Los Angeles, Ca.
90503               90024
(213) 214-1136      (213) 825-9040

email: cracraft@venera.isi.edu
.fi
.sp
Manpage created by Bill Randle (billr@tekred.tek.com), based on
the man page for an earlier release of Gnuchess.
.SH AUTHOR'S COMMENT
.PP
This software is being made available by the Free Software
Foundation under the restrictions described in its license
agreement which accompanies this distribution. This software,
its sources, binaries, documentation and all associated parts
are copyright (C) 1986 by the Free Software Foundation, Inc.
.SH SEE ALSO
.nf
chesstool(6)
dbm(3)
.fi
