/* $Id: errlist.c,v 1.1 1990/09/05 13:35:30 nick Exp $ */
char * sys_errlist[] =
{
/*   0 */	"No error",
/*   1 */	"Arg list too long",
/*   2 */	"Permission denied",
/*   3 */	"Resource temporarily unavailable",
/*   4 */	"Bad file number",
/*   5 */	"Resource busy",
/*   6 */	"No child processes",
/*   7 */	"Resource deadlock would occur",
/*   8 */	"Domain error",
/*   9 */	"Already exists",
/*  10 */	"Bad address",
/*  11 */	"File too large",
/*  12 */	"Interrupted system call",
/*  13 */	"Invalid argument",
/*  14 */	"Input/output error",
/*  15 */	"Wrong operation applied to directory",
/*  16 */	"Too many open files",
/*  17 */	"Too many links",
/*  18 */	"Filename too long",
/*  19 */	"Too many open files in system",
/*  20 */	"No such device",
/*  21 */	"No such file or directory",
/*  22 */	"Exec format error",
/*  23 */	"No locks available",
/*  24 */	"Not enough memory space",
/*  25 */	"No space left on device",
/*  26 */	"Not a directory",
/*  27 */	"Directory not empty",
/*  28 */	"Inappropriate I/O operation",
/*  29 */	"No such device or address",
/*  30 */	"Operation not permitted",
/*  31 */	"Broken pipe",
/*  32 */	"Result too large",
/*  33 */	"Read only file system",
/*  34 */	"Invalid seek",
/*  35 */	"No such process",
/*  36 */	"Improper link",
/*  37 */	"Operation will block",
/*  38 */	"Operation now in progress",
/*  39 */	"Operation already in progress",
/*  40 */	"Socket operation on non-socket",
/*  41 */	"Destination address required",
/*  42 */	"Message too long",
/*  43 */	"Protocol wrong type for socket",
/*  44 */	"Bad protocol option",
/*  45 */	"Protocol not supported",
/*  46 */	"Socket type not supported",
/*  47 */	"Operation not supported on socket",
/*  48 */	"Protocol family not supported",
/*  49 */	"Address family not supported",
/*  50 */	"Address already in use",
/*  51 */	"Cannot assign requested address",
/*  52 */	"Network is down",
/*  53 */	"Network is unreachable",
/*  54 */	"Network dropped connection on reset",
/*  55 */	"Software caused connection abort",
/*  56 */	"Connection reset by peer",
/*  57 */	"No buffer space available",
/*  58 */	"Socket is already connected",
/*  59 */	"Socket is not connected",
/*  60 */	"Cannot send after shutdown",
/*  61 */	"Connection timed out",
/*  62 */	"Connection refused",
/*  63 */	"Host is down",
/*  64 */	"No route to host",
		0
};
int sys_nerr = 65;

char * sys_siglist[] =
{
/*   0 */	"no signal",
/*   1 */	"abort",
/*   2 */	"arithmetic exception",
/*   3 */	"illegal instruction",
/*   4 */	"attention from user",
/*   5 */	"bad memory access",
/*   6 */	"termination request",
/*   7 */	"stack overflow",
/*   8 */	"alarm/timeout signal",
/*   9 */	"hangup",
/*  10 */	"pipe signal",
/*  11 */	"interactive termination",
/*  12 */	"trace trap",
/*  13 */	"user 1",
/*  14 */	"user 2",
/*  15 */	"child termination",
/*  16 */	"urgent data available",
/*  17 */	"continue",
/*  18 */	"stop",
/*  19 */	"interactive stop",
/*  20 */	"background read",
/*  21 */	"background write",
/*  22 */	"window changed",
/*  23 */	"sibling crashed",
/*  24 */	"<Signal: 0x00000018>",
/*  25 */	"<Signal: 0x00000019>",
/*  26 */	"<Signal: 0x0000001a>",
/*  27 */	"<Signal: 0x0000001b>",
/*  28 */	"<Signal: 0x0000001c>",
/*  29 */	"<Signal: 0x0000001d>",
/*  30 */	"<Signal: 0x0000001e>",
/*  31 */	"termination",
		0
};
