
        /* direct functions */
STRING directfns[] = {
        "j    ",
        "ldlp ",
        "pfix ",
        "ldnl ",
        "ldc  ",
        "ldnlp",
        "nfix ",
        "ldl  ",
        "adc  ",
        "call ",
        "cj   ",
        "ajw  ",
        "eqc  ",
        "stl  ",
        "stnl ",
        "opr  "
        };

STRING oper[] = {
        /* one byte operations */
        "rev",
        "lb",
        "bsub",
        "endp",
        "diff",
        "add",
        "gcall",
        "in",
        "prod",
        "gt",
        "wsub",
        "out",
        "sub",
        "startp",
        "outbyte",
        "outword",


        /* two byte operations */
        "seterr",
        0,
        "resetch",
        "csub0",
        0,
        "stopp",
        "ladd",
        "stlb",
        "sthf",
        "norm",
        "ldiv",
        "ldpi",
        "stlf",
        "xdble",
        "ldpri",
        "rem",

        "ret",
        "lend",
        "ldtimer",
        0,
        0,
        0,
        0,
        0,
        0,
        "testerr",
        "testpranl",
        "tin",
        "div",
        0,
        "dist",
        "disc",

        "diss",
        "lmul",
        "not",
        "xor",
        "bcnt",
        "lshr",
        "lshl",
        "lsum",
        "lsub",
        "runp",
        "xword",
        "sb",
        "gajw",
        "savel",
        "saveh",
        "wcnt",

        "shr",
        "shl",
        "mint",
        "alt",
        "altwt",
        "altend",
        "and",
        "enbt",
        "enbc",
        "enbs",
        "move",
        "or",
        "csngl",
        "ccnt1",
        "talt",
        "ldiff",

        "sthb",
        "taltwt",
        "sum",
        "mul",
        "sttimer",
        "stoperr",
        "cword",
        "clrhalterr",
        "sethalterr",
        "testhalterr",
        "dup",
        "move2dinit",
        "move2dall",
        "move2dnonzero",
        "move2dzero",
        0,

        0,
        0,
        0,
        "unpacksn",
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        "postnormsn",
        "roundsn",
        0,
        0,

        0,
        "ldinf",
        "fmul",
        "cflerr",
        "crcword",
        "crcbyte",
        "bitcnt",
        "bitrevword",
        "bitrevnbits",
        0,
        0,
        0,
        0,
        0,
        0,
        0,

        0,
        "wsubdb",
        "fpldnldbi",
        "fpchkerr",
        "fpstnldb",
        0,
        "fpldnlsni",
        "fpadd",
        "fpstnlsn",
        "fpsub",
        "fpldnldb",
        "fpmul",
        "fpdiv",
        0,
        "fpldnlsn",
        "fpremfirst",

        "fpremstep",
        "fpnan",
        "fpordered",
        "fpnotfinite",
        "fpgt",
        "fpeq",
        "fpi32tor32",
        0,
        "fpi32tor64",
        0,
        "fpb32tor64",
        0,
        "fptesterr",
        "fprtoi32",
        "fpstnli32",
        "fpldzerosn",

        "fpldzerodb",
        "fpint",
        0,
        "fpdup",
        "fprev",
        0,
        "fpldnladddb",
        0,
        "fpldnlmuldb",
        0,
        "fpldnladdsn",
        "fpentry",
        "fpldnlmulsn",
        0,
        0,
        0
        };

        /* three byte operations */
STRING oper3[] = {
        0,
        "fpusqrtfirst",
        "fpusqrtstep",
        "fpusqrtlast",
        "fpurp",
        "fpurm",
        "fpurz",
        "fpur32tor64",
        "fpur64tor32",
        "fpuexpdec32",
        "fpuexpinc32",
        "fpuabs",
        0,
        "fpunoround",
        "fpuchki32",
        "fpuchki64"
        };

