#!/bin/csh
# Make Helios/C40 on a hp snake

setenv HPROC C40
setenv HHOST HP

set hsrc=/hsrc
setenv HSRC  $hsrc

setenv HPROD /hprod/C40

setenv HHOSTBIN /usr/local/bin

if (-e HP) then
	cd HP; make $*
else
       	make $*
endif
