#!/bin/bash
# Make Helios/TRAN on Linux

export HPROC=TRAN
export HHOST=LINUX

export HSRC=/giga/HeliosRoot/Helios-NG

export HPROD=/giga/HeliosRoot/Production/TRAN

export HHOSTBIN=/giga/bin_linux

export HLICENSEE=PERIHELION

export NCFLAGS=-D__CROSSCOMP

export C_LIBDIR=$HPROD/lib/
export C_INCDIR=$HSRC/include
export C_COMPILER==$HHOSTBIN/nc
export LINKER=$HHOSTBIN/asm
export ASSEMBLER=$HHOSTBIN/asm
export GCCINCLUDE=/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include

export NEW_NCC=OLD_TRAN

if [ -d LINUX ]; then
	cd LINUX; make $*
else
       	make $*
fi

