#!/bin/csh
# Make Helios/ARM on a RS6000

setenv HPROC ARM
setenv HHOST RS6000

set hsrc=/hsrc
setenv HSRC  $hsrc

setenv HPROD /hprod/ARM

setenv HHOSTBIN /pds/bin

if (-e RS6000) then
	cd RS6000; gmake $*
else
       	gmake $*
endif
