#!/bin/csh
# Helios make script, RS6000 host to make Helios/C40

# Processor version to build
setenv HPROC C40

# Host we are building on
setenv HHOST RS6000

# Where the helios source is situated
setenv HSRC  /hsrc

# Where to install helios binaries
setenv HPROD /hprod/C40

# Where to place host utilities
setenv HHOSTBIN /pds/bin

# Define where to get remote files (RSRC support)
#setenv HSRC  /lsrc
#setenv RSRC  /hsrc

#make single processor version for the time being
#setenv HSINGLEPROC TRUE			# type of system
setenv  HLICENSEE   PERIHELION_C40		# source licensee
#setenv SYSDEB      SYSDEB			# make debugging version of system

setenv NEW_NCC C40
setenv C_COMPILER /pds/bin/ccc40
setenv LINKER     /pds/bin/ldc40
setenv ASSEMBLER  /pds/bin/asc40
setenv MACRO      /pds/bin/ampp
setenv MACDIR     /hsrc/include/ampp/
setenv C_LIBDIR   /hprod/C40/lib/
setenv C_INCDIR   /hsrc/include/

# Make it!
if (-e C40) then
	cd C40; gmake -w $*
else
	gmake -w $*
endif
