#!/bin/csh
# Make Helios/68K on a RS6000

setenv HPROC 68K
setenv HHOST RS6000

set hsrc=/hsrc
setenv HSRC  $hsrc

setenv HPROD /hprod/68K

setenv HHOSTBIN /pds/bin

if (-e RS6000) then
	cd RS6000; gmake $*
else
       	gmake $*
endif
