#! /bin/sh

USAGE="Usage: $0 manfile helpfile"

case $# in
2)	infile=$1;
	outfile=$2;;
*)	echo $USAGE;
	exit 1;;
esac

T=/usr/lib/tmac

nroff -Tcrt -mjt $infile | sed -f $T/sedf1 | sed -f $T/sedf2 > $outfile
