@ generated by Norcroft Helios ARM C vsn 3.00/345 [May 31 1990]

dp      .req    r9
sl      .req    r10
fp      .req    r11
ip      .req    r12
sp      .req    r13
lr      .req    r14
pc      .req    r15

        .text

        .ascii  "main"
        .ascii  "\0\0\0\0"
        .word   0xff000008


        .global _main
_main:

        mov     ip, sp
        stmfd   sp!, {fp,ip,lr,pc}
        sub     fp, ip, #4
        cmp     sp, sl
        bllt    ___stack_overflow
        add     r0, pc, #L000030-.-8
        bl      __printf
        mov     r0, #0
        ldmea   fp, {fp,sp,pc}^
L000030:

        .ascii  "Hell"
        .ascii  "o Sp"
        .ascii  "lit "
        .ascii  "Modu"
        .ascii  "le T"
        .ascii  "able"
        .ascii  " wor"
        .ascii  "ld ("
        .ascii  "2)\n\0"

        ldr     ip, [dp, #4]
        add     ip, ip, #0
        ldr     ip, [ip, #0]
        mov     pc, ip

        ldr     ip, [dp, #4]
        add     ip, ip, #0
        ldr     ip, [ip, #0]
        mov     pc, ip

        .word   0x00000000

        ldr     ip, [dp, #0]
        cmp     r0, #2
        bne     L000090
        sub     r1, pc, #128
        str     r1, [ip], #4
        movs    pc, lr
L000090:
        movs    pc, lr
