default:
	@ cd .. ; unset MAKEFLAGS ; $(MAKE) ncc-SUN4

all:
	@ cd .. ; unset MAKEFLAGS ; $(MAKE) all

clean:
	@ cd .. ; unset MAKEFLAGS ; $(MAKE) clean-SUN4

install:
	@ cd .. ; unset MAKEFLAGS ; $(MAKE) install-SUN4

