/*> helios/h
 * Title:       Helios Object Format
 * Status:      C Library Extension
 * Author:      JGSmith
 * Copyright:   Copyright (C) 1990 Active Book Company Limited
 *
 * This header defines the essential structure of the Helios Object Format.
 */

#ifndef _helios_h
#define _helios_h

/*---------------------------------------------------------------------------*/

#ifndef int32
#define int32 long int  /* a standard unit */
#endif

/*---------------------------------------------------------------------------*/

typedef struct {
                unsigned int helios_module ; /* defined module number */
                unsigned int helios_nsyms ;  /* no. of symbols in this file */
               } HOF_header ;

/*---------------------------------------------------------------------------*/

#define BYTESEX_EVEN
#define locase(c)       (isupper(c) ? tolower(c) : c)
#define eqs(a,b)        (strncmp(a,b,31) == 0)
#define use(x)          ((x) = (x))

#define HOF_t_code              0x01
#define HOF_t_bss               0x02
#define HOF_t_init              0x03

#define HOF_t_byte              0x09   /* ls 3 bits = size */
#define HOF_t_short             0x0A
#define HOF_t_word              0x0C

#define HOF_t_codesymbol        0x0D
#define HOF_t_imagesize         0x0E
#define HOF_t_labelref          0x0F
#define HOF_t_dataref           0x10
#define HOF_t_datamod           0x11
#define HOF_t_modnum            0x12

#define HOF_t_patch             0x13
#define HOF_t_maxpatch          0x1F

#define HOF_t_patch_m68kadd     0x13
#define HOF_t_patch_m68kshift   0x14
#define HOF_t_patch_armdt       0x15    /* data xfer */
#define HOF_t_patch_armdp       0x16    /* data proc */
#define HOF_t_patch_armjp       0x17    /* jmp */
#define HOF_t_patch_armdplsb    0x18    /* data proc lsbyte (bits 0..7) */
#define HOF_t_patch_armdpmid    0x1A    /* data proc midbyte (bits 8..15) */
#define HOF_t_patch_armdprest   0x19    /* data proc remaining residue */

#define HOF_t_patch_swap        0x1E
#define HOF_t_patch_pgc1        0x1F

#define HOF_t_module            0x20
#define HOF_t_bytesex           0x21
 
#define HOF_t_global            0x22
#define HOF_t_label             0x23
#define HOF_t_data              0x24
#define HOF_t_common            0x25
#define HOF_t_codetable         0x26

#define HOF_t_newseg            0x30
#define HOF_t_end               0x31
#define HOF_t_literal           0x32   /* t_code of <= 4 bytes */

#define HOF_s_unbound           0x40
#define HOF_s_codesymb          0x41
#define HOF_s_datasymb          0x42
#define HOF_s_commsymb          0x43
#define HOF_s_datadone          0x44
#define HOF_s_commdone          0x45

/* traceing */
#define HOF_db_gencode          0x0008
#define HOF_db_genimage         0x0010
#define HOF_db_files            0x0400
#define HOF_db_mem              0x0800
#define HOF_db_sym              0x1000
#define HOF_db_modules          0x2000
#define HOF_db_scancode         0x4000

/*---------------------------------------------------------------------------*/
/* ARM instructions generated by Helios updates */

/* "LDR <r>,[dp,#&00]" */
#define LDRfromdp(r)     (0xE5990000 | ((r) << 12))

/* "ADD <r>,<r>,#&00" */
#define ADDwithoffset(r) (0xE2800000 | ((r) << 16) | ((r) << 12))

/* "LDR <r>,[<r>,#&00]" */
#define LDRfromoffset(r) (0xE5900000 | ((r) << 16) | ((r) << 12))

/* "LDRB <r>,[<r>,#&00]" */
#define LDRBfromoffset(r) (0xE5D00000 | ((r) << 16) | ((r) << 12))

/* "STR <r>,[<r>,#&00]" */
#define STRtooffset(r) (0xE5800000 | ((r) << 16) | ((r) << 12))

/* "STRB <r>,[<r>,#&00]" */
#define STRBtooffset(r) (0xE5C00000 | ((r) << 16) | ((r) << 12))

/* "MOVNV r0,r0"        NOP */
#define ARMNOP  (0xF1A00000)            /* do nothing for 1cycle */

/* "MOVS pc,ip"             */
#define stubCall (0xE1A0F00C)           /* call a function from a stub */

/* Exception stub code (nasty constants) */
#define stubPush  (0xE92D5000)		/* "STMFD sp!,{ip,lk}" */
#define stubStore (0xE58DC004)		/* "STR   ip,[sp,#4]"  */
#define stubPop	  (0xE8Bd9000)		/* "LDMFD sp!,{ip,pc}" */

/*---------------------------------------------------------------------------*/
#endif /* _helios_h */

/*> EOF helios/h <*/
