@echo off
if %HSRC%x==x set HSRC= 
if %INCLUDE%x==x set INCLUDE= 
if %MACRO%x==x set MACRO= 
if %CC%x==x set CC= 
if %MS_CC%x==x set MS_CC= 
if %LD%x==x set LD= 
if %HLD%x==x set HLD= 
if %ASM%x==x set ASM= 
if %HASM%x==x set HASM= 
if %AMPP%x==x set AMPP= 
if %PLAT%x==x set PLAT= 
if %ARM_CC_FLAGS%x==x set ARM_CC_FLAGS= 
if %DEFINES%x==x set DEFINES= 
if %LDFLAGS%x==x set LDFLAGS= 
if %HLDFLAGS%x==x set HLDFLAGS= 
if %ASMFLAGS%x==x set ASMFLAGS= 
if %HASMFLAGS%x==x set HASMFLAGS= 
if %TYPE%x==x set TYPE= 
if %AMPPFLAGS%x==x set AMPPFLAGS= 
if %INCLUDES%x==x set INCLUDES= 
if %HINCLUDE%x==x set HINCLUDE= 
if %RM%x==x set RM= 
if %DEST%x==x set DEST= 
