#! /bin/sh
# @(#)ivalid.sh	1.1	89/10/27
##############################################################################
#
#	Copyright (C) 1989 INMOS Ltd.  All rights reserved
#
#	Produced by K-par Systems Ltd.
#
#  Program/Library:	ivalid - iserver validation program
#
#  Purpose: 		Shell script to run validation
#
#  Author:		Chris Farey (K-par) 9-Oct-1989
#
#---------------------------------------------------------------------------*/
#
# Initialisation
#
# Set up an environment variable
#
CALIGULA=WAS_A_ROMAN
export CALIGULA
#
# Ensure all tempory files set up by the test are removed
#
rm -f /tmp/ivl_testfile1
rm -f /tmp/ivl_testfile2
rm -f /tmp/ivl_filetest3
rm -f /tmp/ivl_renamed
rm -f /tmp/ivl_not_there
#
scfile="/tmp/ivl_touch"
rm -f $scfile
#
# Run the program
#
iserver -sa -ss -si -sc /vol/local/transputer/ivalid.b4h -these ARE Not iserver -PARAMETERS
status=$?
#
# Check results of run
#
if [ -f $scfile ] ; then
    rm -f $scfile
else
    echo " "
    echo -- System command \"touch $scfile\" failed to create $scfile
    status=1
fi
#
# Display final status
#
if [ $status -ne 0 ] ; then
    echo " "
    echo "*** Warning - some of the tests have failed"
else
    echo " "
    echo "All tests completed successfully"
fi
